### ISSUE TITLE
Server List MOTD

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomCore#53]
Ability to have multiple MOTDs that cycle through randomly

**Comment by lokka30** [comment]
```
server-list-motd:
 enabled: true
 enabled-motds:
 - 'sale'
 - 'welcome'
 motds:
  sale:
  - 'First line, welcome user.'
  - 'Second line, 70% off sale, /buy.'
  welcome:
  - 'Welcome user.'
  - 'We have minigames and that.'
```
