### ISSUE TITLE
Run commands after the server loads up

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomCore#93]
```
commands-on-server-startup:
 1:
   command: 'weather clear' #execute command /weather clear
   delay: 30 #wait 30 ticks before executing
 2:
  command: 'time set day'
  delay: 0 #will not run the scheduler to save performance
```
